In [2]:
import numpy as np
print (np.__version__)

1.14.3


In [3]:
myPythonList = [1,9,8,3]
numpy_array_from_list = np.array(myPythonList)

numpy_array_from_list

array([1, 9, 8, 3])

In [7]:
# this is the same. combine above operations
a = np.array([1,9,8,3])

array([1, 9, 8, 3])

In [8]:
b = a + 10
b

array([11, 19, 18, 13])

In [9]:
print(a.shape)
print(a.dtype)

(4,)
int32


In [10]:
arr_float = np.array([1.0, 2.0, 3.0, 4.0])
print(arr_float.dtype)

float64


In [11]:
# two dimension
arr_2d = np.array([(1,2,3),(4,5,6)])
print(arr_2d.shape)

(2, 3)


In [12]:
# three dimension
arr_3d = np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
])
print(arr_3d.shape)

(2, 2, 3)


In [13]:
# create matrix of zeros or ones
zeros = np.zeros((2,2))
ones = np.ones((1,2,3))

In [14]:
zeros

array([[0., 0.],
       [0., 0.]])

In [15]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# https://www.guru99.com/numpy-reshape.html
# https://docs.scipy.org/doc/numpy/user/quickstart.html
# http://cs231n.github.io/python-numpy-tutorial/